# Generated by Django 3.1.2 on 2021-02-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='Profile',
            new_name='profile',
        ),
    ]
