# Generated by Django 3.1.2 on 2021-03-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='graduation_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='high_school_passing_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passing_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_graduation_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='graduation_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='high_school_passing_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='other_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='passing_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='post_graduation_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='graduation_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='high_school_passing_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='other_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='passing_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='post_graduation_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='graduation_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='high_school_passing_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='other_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='passing_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='post_graduation_year',
            field=models.CharField(blank=True, default=True, max_length=4, null=True),
        ),
    ]
