# Generated by Django 3.1.4 on 2021-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internattendance',
            name='attendance',
            field=models.CharField(default='absent', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='date',
            field=models.CharField(blank=True, default='06-03-2021', max_length=100),
        ),
    ]
