# Generated by Django 3.1.2 on 2021-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210304_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
    ]
