# Generated by Django 3.1.2 on 2021-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210213_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='intern_id',
            field=models.SlugField(unique=True),
        ),
    ]
