# Generated by Django 3.1.4 on 2021-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210306_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.CharField(blank=True, default='06-03-2021', max_length=100),
        ),
    ]
