# Generated by Django 3.1.2 on 2021-02-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210216_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='intern_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
