# Generated by Django 3.1.4 on 2021-02-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210225_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.CharField(blank=True, default='26/02/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='internattendance',
            name='date',
            field=models.CharField(blank=True, default='26/02/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='traineeattendance',
            name='date',
            field=models.CharField(blank=True, default='26/02/2021', max_length=100),
        ),
        migrations.CreateModel(
            name='TrainerAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, default='26/02/2021', max_length=100)),
                ('trainer_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.trainer')),
            ],
        ),
    ]
