# Generated by Django 3.1.2 on 2021-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210216_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='Profile',
            new_name='profile',
        ),
    ]
