# Generated by Django 3.1.2 on 2021-02-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210218_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gotdetail',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='high_school_percent',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='other_percent',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='post_graduation_percent',
        ),
        migrations.AddField(
            model_name='employee',
            name='emails',
            field=models.EmailField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='refference',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='belongs_department',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='board',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_no',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_no',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_occupation',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduation_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduation_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduation_percent',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduation_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='high_school_board',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='high_school_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='high_school_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='high_school_passing_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='high_school_percent',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_percent',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_card',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passing_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='percent',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pin_code',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_graduation_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_graduation_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_graduation_percent',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_graduation_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_graduation_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='relationships',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='school_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='school_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skill',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
