# Generated by Django 3.1.4 on 2021-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210307_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerattendance',
            name='attendance',
            field=models.CharField(default='absent', max_length=100),
        ),
    ]
