# Generated by Django 3.1.2 on 2021-03-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210304_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
