# Generated by Django 3.1.4 on 2021-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210307_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='tds',
            field=models.CharField(max_length=100),
        ),
    ]
