# Generated by Django 3.1.2 on 2021-02-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210220_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='living_date',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
