# Generated by Django 3.1.2 on 2021-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210222_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intern_attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee_attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='intern',
            name='intern_id',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='trainee_id',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Trainer_id',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='Trainer_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='gotdetail',
        ),
        migrations.AddField(
            model_name='trainer',
            name='emails',
            field=models.EmailField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='joining_date',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainer',
            name='living_date',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainer',
            name='refference',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Profile',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='belongs_department',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='blood_group',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='board',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='company_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contact_no',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='designation',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='father_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='father_no',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='father_occupation',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='graduation_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='graduation_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='graduation_percent',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='graduation_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='high_school_board',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='high_school_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='high_school_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='high_school_passing_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='high_school_percent',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='join_date',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='other_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='other_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='other_percent',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='other_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='other_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pan_card',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='passing_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='percent',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pin_code',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='position',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='post_graduation_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='post_graduation_percent',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='post_graduation_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='post_graduation_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='relationships',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='school_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='school_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='skill',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='state',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
