# Generated by Django 3.1.2 on 2021-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210226_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='internattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='traineeattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
    ]
