# Generated by Django 3.1.2 on 2021-03-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210301_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document_zip',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='intern',
            name='document_zip',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='document_zip',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='document_zip',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
