# Generated by Django 3.1.4 on 2021-02-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210223_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='attendance',
        ),
        migrations.AddField(
            model_name='internattendence',
            name='intern_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.intern'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='blood_group',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='board',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='date_of_birth',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='email',
            field=models.EmailField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='father_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='father_no',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='father_occupation',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='graduation_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='graduation_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='graduation_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='high_school_board',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='high_school_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='high_school_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='high_school_passing_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='intern_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='join_date',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='other_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='other_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='other_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='other_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='passing_year',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='pin_code',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='post_graduation_degree',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='post_graduation_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='post_graduation_univercity',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='profile',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='school_marksheet',
            field=models.FileField(blank=True, default=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='school_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='state',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
