# Generated by Django 3.1.4 on 2021-03-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='internattendance',
            name='attendance',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='internattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='traineeattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='date',
            field=models.CharField(blank=True, default='01/03/2021', max_length=100),
        ),
    ]
