# Generated by Django 3.1.2 on 2021-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210305_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='date_of_birth',
            field=models.DateField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='date_of_birth',
            field=models.DateField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(blank=True, default=True, null=True),
        ),
    ]
