# Generated by Django 3.1.4 on 2021-02-24 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210224_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internattendence',
            name='date',
        ),
        migrations.AddField(
            model_name='internattendence',
            name='last_reply',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
