# Generated by Django 3.1.4 on 2021-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210302_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('regarding', models.CharField(blank=True, default=True, max_length=100, null=True)),
                ('reference', models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('linkain', 'linkain'), ('twitter', 'twitter'), ('other', 'other'), ('people', 'people')], max_length=100, null=True)),
                ('message', models.CharField(blank=True, default=True, max_length=100, null=True)),
            ],
        ),
    ]
