# Generated by Django 3.1.2 on 2021-02-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210224_0537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_attendence',
        ),
        migrations.DeleteModel(
            name='Intern_attendence',
        ),
        migrations.DeleteModel(
            name='Staff_attendence',
        ),
        migrations.DeleteModel(
            name='Trainee_attendence',
        ),
        migrations.DeleteModel(
            name='Trainer_attendence',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='graduation_marksheet',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='high_school_marksheet',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='other_marksheet',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='post_graduation_marksheet',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='school_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='graduation_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='graduation_percent',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='high_school_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='other_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='post_graduation_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='school_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='graduation_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='graduation_percent',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='high_school_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='high_school_percent',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='other_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='other_percent',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='post_graduation_marksheet',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='post_graduation_percent',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='school_marksheet',
        ),
    ]
