# Generated by Django 3.1.4 on 2021-03-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210301_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internattendance',
            name='attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=100),
        ),
    ]
