# Generated by Django 3.1.4 on 2021-02-24 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210224_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internattendence',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
