# Generated by Django 3.1.4 on 2021-03-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210301_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='refrence',
            new_name='reference',
        ),
    ]
