# Generated by Django 3.1.4 on 2021-02-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210224_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternAttendence',
            new_name='InternAttendance',
        ),
    ]
