# Generated by Django 3.1.4 on 2021-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210224_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internattendance',
            name='date',
            field=models.CharField(blank=True, default='24/02/2021', max_length=100),
        ),
    ]
