# Generated by Django 3.1.2 on 2021-02-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210224_1628'),
        ('dashboard', '0011_auto_20210224_1726'),
    ]

    operations = [
    ]
