# Generated by Django 3.1.4 on 2021-02-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210224_1726'),
        ('dashboard', '0015_auto_20210224_1628'),
    ]

    operations = [
    ]
