# Generated by Django 3.1.4 on 2021-03-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210302_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='attendance',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
