# Generated by Django 3.1.4 on 2021-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210302_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internattendance',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
